import { afterEach, beforeAll, describe, expect, test } from "bun:test";
import { first, second } from ".";
import { getInput, testConfig } from "../utils";

const day = 7;
const year = new Date().getFullYear();

const EXAMPLE_INPUT = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`;

//0  .......S.......
//1  ...............
//2  .......7.......
//3  ...............
//4  ......6.8......
//5  ...............
//6  .....5.7.9.....
//7  ...............
//8  ....4.6...0....
//9  ...............
//10 ...3.5...9.1...
//11 ...............
//12 ..2...6.....2..
//13 ...............
//14 .1.3.5.7.9...3.
//15 ...............

const PUZZLE_INPUT = await getInput({ year, day });

describe(`Day ${day}`, async () => {
  afterEach(() => {
    testConfig.log = false;
  });

  test(`Day ${day} Example`, () => {
    testConfig.log = true;

    const answer = first(EXAMPLE_INPUT);
    expect(answer).toBe(21);
  });

  test(`Day ${day} Solution`, async () => {
    const answer = first(PUZZLE_INPUT);
    console.log({ answer });
    expect(answer).toBeLessThan(1712);
  });

  test(`Day ${day} 2nd Example`, () => {
    testConfig.log = true;

    const answer = second(EXAMPLE_INPUT);
    expect(answer).toBe(40);
  });

  test.skip(`Day ${day} 2nd Solution`, async () => {
    const answer = second(PUZZLE_INPUT);
    console.log({ answer });
    expect(answer).toBeLessThan(1712);
  });
});
